# Generated by Django 3.2.9 on 2021-11-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20, unique=True, verbose_name='客户端编号')),
                ('points', models.IntegerField(default=1, verbose_name='分数')),
            ],
            options={
                'ordering': ['-points', '-id'],
            },
        ),
    ]
